# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        # setup the default resolver
        default:
            # use the default web path
            web_path: ~
    filter_sets:
        cache: ~
        thumbnail:
            quality: 75
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: inset
        memberPicture:
            quality: 100
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: inset
        cafet:
            quality: 100
            filters:
                downscale:
                    max: [ 80, 80 ]


