nelmio_api_doc:
    documentation:
        info:
            title: Asso'esaip API
            description: This API is in development.
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns: [ ^/api(?!/doc$) ]

