vich_uploader:
    db_driver: orm

    mappings:
        profile_pic:
            uri_prefix: /images/profile-pics
            upload_destination: '%kernel.project_dir%/public/images/profile-pics'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        project_logo:
            uri_prefix: /images/project-logos
            upload_destination: '%kernel.project_dir%/public/images/project-logos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
